export type ProjectStatus = 'active' | 'prototype' | 'paused';

export type Project = {
  slug: string;
  name: string;
  description: string;
  language: 'TypeScript' | 'Rust' | 'Python';
  repo: string;
  status: ProjectStatus;
  hue: number;
  image?: string;
  tech: string[];
  github: string;
  links?: {
    label: string;
    href: string;
  }[];
  why: string;
  architecture: string;
  howItWorks: string[];
  decisions: { choice: string; reasoning: string }[];
};

const github = (repo: string) => `https://github.com/Byrrajus12/${repo}`;
const d = (slug: string, tech: string[], why: string, architecture: string, howItWorks: string[], decisions: Project['decisions']): Partial<Project> => ({ slug, tech, github: github(slug), why, architecture, howItWorks, decisions });

const content: Record<string, Partial<Project>> = {
  'poker-nights': d('poker-nights', ['TypeScript', 'React 19', 'Next.js 16', 'Tailwind v4', 'Framer Motion', 'Supabase', 'Vercel'], 'In our home poker games, one person is the banker. They handle all the money. Everyone sends their buy-ins to the banker, and at the end the banker figures out who gets paid what, then opens Venmo or Cash App and sends money one by one. Before this app, that meant notes, a calculator, and a lot of back and forth. I built this to make that whole process take about two minutes.', 'groups → sessions → transactions → settlements → payouts', ['Users create groups, bankers start sessions, add players, and record buy-ins. At the end, cash-out totals are used to compute settlements, check discrepancies, and generate a payout list. Each entry deep-links to Venmo or Cash App with the person and amount pre-filled. Supabase Postgres with RLS stores the data. Nine migrations cover atomic session creation, RLS recursion fixes, duplicate settlement prevention, and payment handles. Auth uses (auth) and (main) route groups. The active session UI uses optimistic insertion with a three-second undo window.'], [{ choice: 'Supabase over a custom backend', reasoning: 'I wanted auth, RLS, and realtime for free. The app is session-based and write-heavy, and Supabase handles that without me running a server.' }, { choice: 'Banker-transfer concurrency protection', reasoning: 'The write checks .eq("banker_id", currentUserId) so two people cannot act as banker simultaneously.' }, { choice: 'PWA with full Apple metadata', reasoning: 'The app is used at poker tables, so it needs to work from the home screen without a browser bar.' }, { choice: 'Optimistic buy-in insertion with undo', reasoning: 'Buy-ins appear immediately and write in the background; a three-second undo catches fat-finger entries.' }]),
  mngr: d('mngr', ['Rust', 'TypeScript', 'React', 'Vite', 'Tauri v2', 'Windows Named Pipes', 'PowerShell'], 'I run multiple Claude Code and Codex sessions at the same time and kept losing track of which terminal was doing what. One session is waiting for approval, another finished ten minutes ago, and a third is stuck on a question I did not see. I built mngr to put all of that in one place without taking up screen space.', 'agent hooks → named pipe → rust backend → tauri events → react overlay', ['claude-hook.ps1 and codex-hook.ps1 send agent lifecycle events to a Windows named pipe. lib.rs maintains a state machine per session (Working, WaitingForApproval, WaitingForInput, Idle, Done) and emits Tauri events. React renders a thin edge rail that expands on hover. Permissions use response files that hooks synchronously wait for.'], [{ choice: 'Tauri + Rust over Electron', reasoning: 'The tool watches other tools, so it has to be lighter than them. The binary is about 4MB.' }, { choice: 'Click-through overlay with selective interactivity', reasoning: 'A Rust cursor stream and elementFromPoint switch the rail between passive and interactive states.' }, { choice: 'Terminal-level window jumping on Windows', reasoning: 'Windows makes focusing a specific terminal instance difficult, so I implemented terminal-level jump and Claude Desktop deep links.' }, { choice: 'Named pipes over WebSockets', reasoning: 'The sessions are local. Named pipes are simpler and do not need a port.' }]),
  minima: d('minima', ['Python', 'Fireworks API', 'QLoRA', 'pytest', 'Docker'], "AMD's developer hackathon, track one. Build a hybrid routing agent that answers benchmark tasks using the fewest tokens possible while maintaining 80% accuracy. 2000 people entered. I placed 13th.", 'prompt → classifier → local solver / local model / hosted model → validator → response', ['task_classifier.py applies ordered regex rules, checking code tasks before entity, date, or math cues. The runtime tries deterministic local solvers first, then a local model, then Fireworks. The client retries without reasoning_effort when a model rejects it. The eval suite compares model families on stress and holdout datasets.'], [{ choice: 'QLoRA', reasoning: 'I fine-tuned a quantized model with LoRA to improve benchmark accuracy without the token cost of a full-size model.' }, { choice: 'Local-first pipeline', reasoning: 'Hosted tokens count against the score, so deterministic solvers handle easy categories first.' }, { choice: 'Code categories checked first', reasoning: 'Code structure is distinctive enough for regex and should not be misrouted as math or entity.' }, { choice: 'Threshold-tolerant architecture', reasoning: 'The threshold moved between 50% and 80%; local-first still minimized tokens either way.' }]),
  atelier: d('atelier', ['Python', 'OpenCV', 'NumPy', 'Pillow', 'scikit-image', 'mss', 'PyDirectInput', 'Fireworks VLM', 'React', 'Vite'], 'I wanted to build an agent that paints by looking at a canvas, not by calling an API. The long-term goal is Meccha Chameleon, a game where you paint to hide from seekers. I have not integrated it with the game yet, but it works on browser canvases.', 'screen capture → perception → planner → executor → verifier → loop', ['perception.py computes regional color and edge error. planner.py chooses the worst region, executor.py turns intents into brush strokes, and verifier.py checks whether error decreased. orchestrator.py coordinates the loop. easels/browser_canvas.py handles DPI-aware capture, fiducial localization, and input injection. A React + Vite dashboard shows events in realtime.'], [{ choice: 'Vision-only, no canvas API access', reasoning: 'If the agent can see the canvas and move a mouse, it can paint anywhere, without DOM access or game mods.' }, { choice: 'OpenCV over VLM for perception', reasoning: 'OpenCV is deterministic and cheap. VLM planning is optional in planners/vlm_planner.py.' }, { choice: 'Closed-loop verification', reasoning: 'It checks every stroke batch and retries when the error does not decrease.' }]),
  airaim: d('airaim', ['Python', 'MediaPipe', 'OpenCV', 'NumPy', 'PyDirectInput'], "I've always wanted to play video games with gesture controls. An earlier webcam keyboard had too much latency and complexity, so I scoped down to a mouse and picked Aim Labs.", 'webcam → mediapipe handlandmarker → gesture classifier → cursor motion → os input', ['Open palm moves the cursor. Thumb-index pinch clicks. Fist pauses movement so you can reposition your hand. Sandbox, cursor, and live modes separate testing from real PyDirectInput control.'], [{ choice: 'Relative motion over screen-position mapping', reasoning: 'Relative motion with acceleration, a deadzone, and EMA smoothing feels closer to a real mouse.' }, { choice: 'Hysteresis on pinch detection', reasoning: 'Separate on/off thresholds prevent repeated clicks near the pinch boundary.' }, { choice: 'Coast through tracking dropouts', reasoning: 'The cursor keeps its last velocity briefly before decaying to zero when tracking drops.' }]),
  voiceops: d('voiceops', ['Python', 'Google ADK', 'Gemini', 'Dynatrace MCP', 'FastAPI', 'VAPI', 'Twilio', 'GitHub Actions', 'Google Cloud Run'], 'For the Google Rapid Agent Hackathon, I built an agent that detects a production problem, calls the on-call engineer, explains it, gets verbal rollback approval, and executes it.', 'dynatrace alert → agent → github correlation → vapi voice call → approval → github actions rollback → post-incident analysis', ['Dynatrace alerts are correlated with recent GitHub commits. VAPI calls the on-call engineer; approval triggers GitHub Actions to build and deploy the rollback SHA. After mitigation, DQL analysis, anomaly detection, blast-radius calculation, and a report run. A browser dashboard can resolve the same approval.'], [{ choice: 'Voice call as primary interface', reasoning: 'A phone reaches an engineer away from a laptop; the dashboard is the fallback.' }, { choice: 'Two-phase workflow', reasoning: 'Mitigate first, analyze second. The agent should not run a full RCA while production is still broken.' }, { choice: 'Resolve parent SHA through GitHub', reasoning: 'trigger_github_rollback finds the bad commit parent through the API instead of hardcoding a revision.' }]),
  'meeting-copilot': d('meeting-copilot', ['TypeScript', 'React 19', 'Next.js 16', 'Zustand', 'Groq SDK', 'Whisper', 'React Markdown'], 'Hiring assignment for TwinMind. A browser meeting assistant where you provide a Groq API key, record, transcribe, get suggested responses, and ask questions about the meeting in realtime.', 'microphone → 30s chunks → whisper transcription → live transcript → suggestions / chat', ['useAudioRecorder.ts manages MediaRecorder in 30-second stop/start cycles. Each chunk goes to Whisper. The transcript feeds suggestions and chat through Zustand state. Editable system prompts customize suggestions.'], [{ choice: '30-second chunks over continuous streaming', reasoning: 'Discrete files are simpler and more reliable with Whisper. The tradeoff is a 30-second delay.' }, { choice: 'Client-side API key', reasoning: 'The user provides their Groq key, avoiding backend auth, usage tracking, and billing for this prototype.' }]),
  'token-sniper': d('token-sniper', ['Python', 'Flask', 'Tweepy', 'Requests', 'React'], 'The idea was to monitor Twitter accounts for token mentions, check DEX Screener liquidity and market cap, and trade on Solana when the numbers looked right.', 'twitter polling → contract extraction → dex screener liquidity check → trade decision', ['tweet_scraper.py extracts Solana contract addresses. liquidity_check.py checks the first pair and applies a $10,000 liquidity threshold. The backend tracks contracts, tweet links, and timestamps in CSV. The trading path worked, but public-network trades were MEV sandwiched, so I stopped.'], [{ choice: 'Polling over WebSocket streaming', reasoning: "Tweepy's v2 API made polling simple and seconds of latency was acceptable." }, { choice: 'Stopped before shipping', reasoning: 'The bot could not be profitable against MEV on public Solana networks, so optimizing it further did not make sense.' }]),
  'speaking-challenge': d('speaking-challenge', ['TypeScript', 'React', 'Next.js', 'Tailwind', 'Radix/shadcn', 'Vercel'], 'I wanted to get better at speaking off the cuff: a random topic, one minute, and words to incorporate mid-speech. Difficulty changes reveal timing, not total duration.', 'setup → countdown → timed prompt reveals → finished', ['A state machine (idle, countdown, playing, finished) drives the game. The topic bank has 35 debate-style prompts. Five words appear during the 60-second round. Creator mode mirrors the front camera with delayed reveal and flash overlay.'], [{ choice: 'State machine over scattered timers', reasoning: 'Explicit states keep countdown, playing, and finished behavior easy to reason about.' }]),
  'transcript-editor': d('transcript-editor', ['TypeScript', 'React', 'Next.js', 'Lexical', 'Supabase', 'Python', 'WhisperX', 'Docker'], 'At 7C Lingo, a client needed meeting transcription for union and company meetings. The team had been typing notes manually, and third-party tools were not a good fit.', 'audio upload → whisperx job → transcript segments → rich text editor → export (txt/docx/pdf)', ['WhisperX runs in Docker, then the frontend turns results into speaker-tagged time segments. Each segment has a Lexical editor with bold, italic, color, and highlights. Blur commits Lexical JSON without React state churn. Exports produce DOCX, PDF, or plain text, with Supabase persistence.'], [{ choice: 'Lexical over a simpler editor', reasoning: 'The client needed highlights and speaker color-coding. The tradeoff is complexity.' }, { choice: 'Segment-level editing', reasoning: 'One editor per line makes speaker labels and timestamps simple and avoids one giant document instance.' }]),
  clawvoice: d('clawvoice', ['TypeScript', 'Node.js', 'Commander', 'Express 5', 'Twilio', 'OpenAI TTS', 'Zod'], 'When OpenClaw launched, setting up voice and phone meant implementing a gateway, configuring Twilio, handling TTS, and wiring everything together. I built this as the voice layer around the OpenClaw brain.', 'twilio call → speech gather → openclaw gateway → tts → twiml response', ['init creates starter config and tunnel setup, doctor validates requirements, start launches Express, and call initiates an outbound call. Webhooks gather speech, send it to OpenClaw or a mock agent, generate OpenAI TTS audio, and return TwiML.'], [{ choice: 'Mock mode as default', reasoning: 'The full voice flow can be tested without an OpenClaw account.' }, { choice: 'doctor command for validation', reasoning: 'It checks required environment variables up front instead of failing during a call.' }]),
  'f1-telemetry': d('f1-telemetry', ['TypeScript', 'React 19', 'Next.js 16', 'PixiJS 8', 'Python', 'FastAPI', 'FastF1', 'NumPy', 'Pandas'], 'This was a prototype for visualizing F1 race replays with telemetry data. I stopped after finding better existing tools and realizing it had no clear purpose beyond the technical exercise.', 'fastf1 data → api → track processing → pixi.js renderer → replay controls + leaderboard', ['The backend normalizes FastF1 session data. The frontend processes track geometry, renders 2D car sprites with PixiJS, and runs replay controls. Ranking uses distance progressed rather than raw position, and Barcelona qualifying and race fixtures support offline development.'], [{ choice: 'Distance progressed over raw position', reasoning: 'It makes ranking and overtake detection more accurate around a track.' }, { choice: 'Offline fixtures', reasoning: 'Local Barcelona data makes renderer work possible without fetching session data every time.' }]),
};

const base: Omit<Project, 'tech' | 'github' | 'why' | 'architecture' | 'howItWorks' | 'decisions'>[] = [
  { slug: 'poker-nights', name: 'poker-nights', description: 'Tracks buy-ins and cash-outs for home games.', language: 'TypeScript', repo: 'poker-nights', status: 'active', hue: 58, image: '/card-art/poker-nights.png', links: [{ label: 'Website', href: 'https://226pokernights.vercel.app/' }] },
  { slug: 'mngr', name: 'mngr', description: 'Monitor Claude Code and Codex sessions from one window.', language: 'Rust', repo: 'mngr', status: 'active', hue: 64, image: '/card-art/mngr.png' },
  { slug: 'minima', name: 'minima', description: 'Hybrid routing agent for benchmark tasks.', language: 'Python', repo: 'minima', status: 'prototype', hue: 70, image: '/card-art/minima.png' },
  { slug: 'atelier', name: 'Atelier', description: 'A vision-based agent that paints on browser canvases.', language: 'Python', repo: 'atelier', status: 'active', hue: 76, image: '/card-art/atelier.png' },
  { slug: 'airaim', name: 'AirAim', description: 'Hand tracking used as mouse input.', language: 'Python', repo: 'airaim', status: 'paused', hue: 82, image: '/card-art/airaim.png' },
  { slug: 'voiceops', name: 'VoiceOps', description: 'Voice-driven production incident response.', language: 'Python', repo: 'voiceops-agent', status: 'prototype', hue: 68, image: '/card-art/voiceops.png', links: [{ label: 'Devpost', href: 'https://devpost.com/software/voiceops-7fga5i' }] },
  { slug: 'meeting-copilot', name: 'meeting-copilot', description: 'A browser meeting assistant for transcription and suggestions.', language: 'TypeScript', repo: 'meeting-copilot', status: 'prototype', hue: 62, image: '/card-art/meeting-copilot.png' },
  { slug: 'token-sniper', name: 'token-sniper', description: 'A memecoin trading bot.', language: 'Python', repo: 'token-sniper', status: 'paused', hue: 56, image: '/card-art/token-sniper.png' },
  { slug: 'speaking-challenge', name: 'speakingChallenge', description: 'Impromptu speaking practice.', language: 'TypeScript', repo: 'speakingChallenge', status: 'paused', hue: 72 },
  { slug: 'transcript-editor', name: 'transcript-editor', description: 'Transcript editing with speaker-tagged segments.', language: 'TypeScript', repo: 'transcript_editor', status: 'paused', hue: 78 },
  { slug: 'clawvoice', name: 'ClawVoice', description: 'A voice layer for OpenClaw agents.', language: 'TypeScript', repo: 'ClawVoice', status: 'active', hue: 66 },
  { slug: 'f1-telemetry', name: 'F1-Replay-Telemetry', description: 'A prototype for visualizing F1 race replays.', language: 'TypeScript', repo: 'F1-Replay-Telemetry', status: 'paused', hue: 60 },
];

export const projects: Project[] = base.map((project) => ({ ...project, ...content[project.slug], repo: project.repo, github: github(project.repo) } as Project));
export const carouselProjects = projects.slice(0, 8);
export function getProject(slug: string) { return projects.find((project) => project.slug === slug); }
